# Generated by Django 4.2.4 on 2024-01-27 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('st_population', models.FloatField(blank=True, null=True)),
                ('total_population', models.FloatField(blank=True, null=True)),
                ('W_BMI', models.FloatField(blank=True, null=True)),
                ('C_UW', models.FloatField(blank=True, null=True)),
                ('AN_W', models.FloatField(blank=True, null=True)),
                ('AN_C', models.FloatField(blank=True, null=True)),
                ('AHC_ANC', models.FloatField(blank=True, null=True)),
                ('AHC_Full_ANC', models.FloatField(blank=True, null=True)),
                ('AHC_PNC', models.FloatField(blank=True, null=True)),
                ('AHC_HI', models.FloatField(blank=True, null=True)),
                ('Enrollment', models.FloatField(blank=True, null=True)),
                ('Equity', models.FloatField(blank=True, null=True)),
                ('E_DropRate', models.FloatField(blank=True, null=True)),
                ('S_Sani', models.FloatField(blank=True, null=True)),
                ('S_CoFu', models.FloatField(blank=True, null=True)),
                ('S_DrWa', models.FloatField(blank=True, null=True)),
                ('S_Elec', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(default='1234567890', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
