# Generated by Django 4.2.4 on 2024-02-23 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('total_tribals', models.IntegerField(blank=True, null=True)),
                ('H_DI', models.FloatField(blank=True, null=True)),
                ('E_DI', models.FloatField(blank=True, null=True)),
                ('S_DI', models.FloatField(blank=True, null=True)),
                ('C_DI', models.FloatField(blank=True, null=True)),
                ('G_DI', models.FloatField(blank=True, null=True)),
                ('tribal_incidence', models.FloatField(blank=True, null=True)),
                ('tribal_intensity', models.FloatField(blank=True, null=True)),
                ('TDI', models.FloatField(blank=True, null=True)),
                ('UNC_CD_score', models.FloatField(blank=True, null=True)),
                ('UNC_IM_score', models.FloatField(blank=True, null=True)),
                ('UNC_MC_score', models.FloatField(blank=True, null=True)),
                ('UNC_CM_score', models.FloatField(blank=True, null=True)),
                ('UNC_FS_score', models.FloatField(blank=True, null=True)),
                ('UNC_LE_score', models.FloatField(blank=True, null=True)),
                ('UNC_DRO_score', models.FloatField(blank=True, null=True)),
                ('UNC_IC_score', models.FloatField(blank=True, null=True)),
                ('UNC_OW_score', models.FloatField(blank=True, null=True)),
                ('UNC_SANI_score', models.FloatField(blank=True, null=True)),
                ('UNC_FUEL_score', models.FloatField(blank=True, null=True)),
                ('UNC_DRWA_score', models.FloatField(blank=True, null=True)),
                ('UNC_ELECTR_score', models.FloatField(blank=True, null=True)),
                ('UNC_ASS_score', models.FloatField(blank=True, null=True)),
                ('UNC_LAN_score', models.FloatField(blank=True, null=True)),
                ('UNC_ARTS_score', models.FloatField(blank=True, null=True)),
                ('UNC_EV_score', models.FloatField(blank=True, null=True)),
                ('UNC_MEET_score', models.FloatField(blank=True, null=True)),
                ('CEN_CD_score', models.FloatField(blank=True, null=True)),
                ('CEN_IM_score', models.FloatField(blank=True, null=True)),
                ('CEN_MC_score', models.FloatField(blank=True, null=True)),
                ('CEN_CM_score', models.FloatField(blank=True, null=True)),
                ('CEN_FS_score', models.FloatField(blank=True, null=True)),
                ('CEN_LE_score', models.FloatField(blank=True, null=True)),
                ('CEN_DRO_score', models.FloatField(blank=True, null=True)),
                ('CEN_IC_score', models.FloatField(blank=True, null=True)),
                ('CEN_OW_score', models.FloatField(blank=True, null=True)),
                ('CEN_SANI_score', models.FloatField(blank=True, null=True)),
                ('CEN_FUEL_score', models.FloatField(blank=True, null=True)),
                ('CEN_DRWA_score', models.FloatField(blank=True, null=True)),
                ('CEN_ELECTR_score', models.FloatField(blank=True, null=True)),
                ('CEN_ASS_score', models.FloatField(blank=True, null=True)),
                ('CEN_LAN_score', models.FloatField(blank=True, null=True)),
                ('CEN_ARTS_score', models.FloatField(blank=True, null=True)),
                ('CEN_EV_score', models.FloatField(blank=True, null=True)),
                ('CEN_MEET_score', models.FloatField(blank=True, null=True)),
                ('village_details', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(default='1234567890', on_delete=django.db.models.deletion.CASCADE, related_name='tribe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='User_Hitcounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_views', models.IntegerField(default=0)),
                ('last_refresh_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tribe_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image', models.ImageField(upload_to='images/logo_images')),
                ('main_image', models.ImageField(upload_to='images/main_images')),
                ('main_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('village_image', models.ImageField(upload_to='images/village_images')),
                ('village_desc', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('map_image', models.ImageField(upload_to='images/map_images')),
                ('date', models.DateField(blank=True, null=True)),
                ('tribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tribe_image', to='home.tribe')),
            ],
        ),
    ]
