# Generated by Django 4.2.4 on 2024-02-23 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tribe',
            name='ARTS_contri_to_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='ASS_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='CD_contri_to_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='CM_contri_to_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='C_contri_to_TDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='DRO_contri_to_E',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='DRWA_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='ELECTR_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='EV_contri_to_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='E_contri_to_TDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='FS_contri_to_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='FUEL_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='G_contri_to_TDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='H_contri_to_TDI',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='IC_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='IM_contri_to_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='LAN_contri_to_C',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='LE_contri_to_E',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='MC_contri_to_H',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='MEET_contri_to_G',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='OW_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='SANI_contri_to_S',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tribe',
            name='S_contri_to_TDI',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
