# Generated by Django 4.2.4 on 2024-03-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_tribe_arts_contri_to_c_tribe_ass_contri_to_s_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report_Excel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('file', models.FileField(upload_to='user_excel_reports/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excel_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User_Hitcounts',
        ),
    ]
