# Generated by Django 4.2.4 on 2024-05-07 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_report_excel_delete_user_hitcounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Report_Excel',
        ),
    ]
